# Generated by Django 2.0.10 on 2019-02-02 09:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='For optimal quality, we recommend that you choose images that are at least 1600px wide', null=True, upload_to='product/category/%Y/%m/%d', verbose_name='image')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='description2')),
                ('background_image', models.ImageField(blank=True, help_text='For optimal quality, we recommend that you choose images that are at least 1600px wide', null=True, upload_to='product/%Y/%m/%d', verbose_name='background_image')),
                ('background_image_cropping', image_cropping.fields.ImageRatioField('background_image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='background image cropping')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='title')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('category', models.ManyToManyField(blank=True, to='product.Category', verbose_name='categories')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('related_product', models.ManyToManyField(blank=True, related_name='_product_related_product_+', to='product.Product', verbose_name='related products')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='For optimal quality, we recommend that you choose images that are at least 1600px wide', upload_to='product/product/%Y/%m/%d', verbose_name='image')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping')),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='title')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cost price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.variant_file_upload_to, verbose_name='image')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1600x1600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sale price')),
                ('slug', models.SlugField(max_length=206, unique=True, verbose_name='slug')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT %')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'products variant',
                'ordering': ['name'],
            },
        ),
    ]
